# Generated by Django 4.1.6 on 2023-02-22 12:38

from django.db import migrations, models
import golf.validators


class Migration(migrations.Migration):

    dependencies = [
        ("golf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="restaurant_link",
            field=models.URLField(
                max_length=500, validators=[golf.validators.validate_restaurant_link]
            ),
        ),
    ]
