# Generated by Django 4.1.6 on 2023-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("golf", "0002_alter_review_restaurant_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="intor",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                default="default_profile_pic.jpg", upload_to="profile_pics"
            ),
        ),
    ]
