# Generated by Django 4.1.6 on 2023-02-27 04:07

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_category_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=1),
            preserve_default=False,
        ),
    ]
