# Generated by Django 4.1.6 on 2023-02-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("golf", "0003_user_intor_user_profile_pic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="intor",
            new_name="intro",
        ),
    ]
