# Generated by Django 4.1.6 on 2023-02-24 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("golf", "0006_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
