# Generated by Django 4.1.6 on 2023-02-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("golf", "0008_like"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-dt_created"]},
        ),
    ]
